### PR TITLE
after analysist data

### PR DESCRIPTION
**Pull request by mammon573**
Hi, John, this is the after analysist CHR data, we removed z_score,  95_CI value and also factors which contains more than half missing value. I will later upload the documentation and put it into the app, so the app will use the new data

### CODE REVIEW

**Comment by olyerickson** [comment]
Have you fully tested? If so I'll grant this. We have a demo tomorrow so I don't want to break anything...

**Comment by mammon573** [comment]
Hi John, I think you can grant this "request" because this is a new data 
frame file. The app is still using the original version, I don't change 
that part this time. I will change the app after the demo.

Sincerely,
Jiangshan Lin

**Comment by RossDeVito** [comment]
This change should just overwrite the old file, not introduce a new one unless there is some clear reason

**Comment by mammon573** [comment]
I am not gonna be here today but I will ask Joy to help me merge it

**Comment by olyerickson** [comment]
I'm allowing this merge. Please test the fully merged master!

**Pull request merged**
